MPD.new(): Read standard environmental variables
kAworu/lua-mpd pull request #3
Opened 2018-09-19 21:52 UTC by doronbehar

Parse $MPD_HOST when evaluating password and host.

2018-09-20 09:16 UTC, kaworu requested changes

2018-09-20 09:16 UTC, kAworu commented on mpd.lua
> +    client.port     = settings.port or os.getenv('MPD_PORT') or 6600
I think we need `tonumber()` the `MPD_PORT` env variable

2018-09-20 09:16 UTC, kAworu commented
Thanks for this PR, I like the idea! See my concern about the port settings, otherwise LGTM.

2018-09-20 15:53 UTC, doronbehar commented
Agreed.

2018-09-21 10:02 UTC, kaworu commented
@doronbehar Thanks! I'll try to find the time to test, merge and release this weekend :)

2018-09-21 10:03 UTC, kaworu approved these changes

2018-10-02 19:13 UTC, kAworu commented
@doronbehar Hi there, sorry for the delay.

So after a quick test, this patch fail when `MPD_HOST` is set to `localhost` (or not set since it is the default). The regexp find fail, and then `env_hostname` is `nil` which cause connect to fail.

Since it is becoming heavier, I think it would be cleaner to extract the env parsing stuff to a function, so that we can do something like that from the constructor:
```lua
env_hostname, env_port, env_password = mpd_getenv()
```

Also, I would love to see the constructor comment and README updated accordingly.

Best Regards,
Alex

2018-10-02 19:13 UTC, kaworu requested changes

2018-10-02 19:13 UTC, kAworu commented on mpd.lua
> +    local _, _, env_password, env_hostname = string.find(env_host, "([^@]+)@([a-zA-Z0-9.]+)")
After this, `env_hostname` could be `nil`

2018-10-03 17:28 UTC, doronbehar commented
Totally agree with you, I've pushed several commits which hopefully fix it.

One question: As for parsing the hostname part of `$MPD_HOST`, what do you think about using a regular expression such as this: https://stackoverflow.com/a/106223/4935114 ?

2018-10-12 19:57 UTC, kAworu commented
Hi @doronbehar,

So I've tested and the patch is working fine now when `$MPD_HOST` and/or `$MPD_PORT` are not defined.

Not a big fan of the regexp from SO as `MPD_HOST` may be a hostname, IPv4, IPv6, or even a path to a Unix domain socket. Note that at the moment we don't support IPv6 (because lua-socket doesn't have released support for it AFAIK) nor Unix domain socket (could be done if someone wanted to). So the regexp from your patch looks fine to me.

Thanks !

2018-10-12 19:57 UTC, merged

2018-10-12 20:19 UTC, kAworu commented
@doronbehar https://luarocks.org/modules/kAworu/mpd/1.2.0-1